### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by mbabuskov** [dernyn/256#1]
Hi,

could you please include a license file. Is the commercial use allowed? For example, including this font in a hex editor component of a larger program or such? Thanks.

**Comment by revelt** [comment]
yeah, what's the licence? Because if it's missing by default it's standard copyright as far as Law is concerned..

**Comment by revelt** [comment]
Please add a `licence.txt` or `licence.md`

**Comment by dernyn** [comment]
added statement and file.
issue resolved

**Comment by revelt** [comment]
awesome! 👍
